// const domain = 'https://qinyuan-test.yunext.com'

var apiConfig = {
	// *****产品管理*****
	// 获取产品信息
	manage_product_getInfo: 'manage/product/getInfo',
	// 产品列表信息
	manage_product_list: 'manage/product/list',
	// 修改产品信息
	manage_product_update: 'manage/product/update',
	// 产品配置文件图片
	manage_productFile_getProductFileInfo: 'manage/productFile/getProductFileInfo',
	// 保存配置文件
	manage_productFile_saveProductFile: 'manage/productFile/saveProductFile',
	//  修改设备流量修正
	manage_waterConfig_saveWaterCorrectConfig: 'manage/waterConfig/saveWaterCorrectConfig',
	// 下载文件
	getFilesAfterDelete: '/web/api/common/getFilesAfterDelete',

	// *****设备管理*****
	// 设备详情
	manage_device_detail: 'manage/device/detail',
	// 设备列表
	manage_device_list: 'manage/device/list',
	// 获取设备总数
	manage_device_deviceCount: 'manage/device/deviceCount',
	// 设备新增趋势概况
	manage_device_trend_deviceCount: 'manage/device/trend/deviceCount',
	// 解绑设备
	manage_user_unbind_device: 'manage/user/unbind/device',
	// 获取设备租期详情
	manage_deviceLease_getDeviceLeaseInfo: 'manage/deviceLease/getDeviceLeaseInfo',
	// 保存设备租期
	manage_deviceLease_saveDeviceLease: 'manage/deviceLease/saveDeviceLease',
	// 清除2G设备故障
	manage_device_cleanIOTDeviceError: 'manage/device/cleanIOTDeviceError',
	// 清除wifi设备故障
	manage_device_cleanIlopDeviceError: 'manage/device/cleanIlopDeviceError',
	// 设置设备节能时间
	manage_deviceSaveEnergy_saveDeviceSaveEnergy: 'manage/deviceSaveEnergy/saveDeviceSaveEnergy',
	// 设备趋势列表
	manage_device_trend_list: 'manage/device/trend/list',
	// 获取水质信息 TDS 浊度 余氯
	manage_deviceProperties_getDevicePropertiesInfo: 'manage/deviceProperties/getDevicePropertiesInfo',
	// 设备详情顶部数据
	manage_device_getIoTDeviceLeaseAndTraffic: 'manage/device/getIoTDeviceLeaseAndTraffic',
	// 绑定用户列表
	manage_device_detail_bindDeviceList: 'manage/device/detail/bindDeviceList',
	// 用户分享列表
	manage_device_detail_shareUser_list: 'manage/device/detail/shareUser/list',
	// 获取故障报警列表
	manage_device_detail_deviceError_trend_list: 'manage/device/detail/deviceError/trend/list',
	// 获取调试历史
	manage_deviceAuth_getDeviceLeaseAuthList: 'manage/deviceAuth/getDeviceLeaseAuthList',
	// 发送重置调试次数
	manage_deviceDebug_resetDeviceLeaseDebug: 'manage/deviceDebug/resetDeviceLeaseDebug',
	// 2G设备解绑
	manage_device_iotRemoveBindUser: 'manage/device/iotRemoveBindUser',
	// 解绑分享用户设备
	manage_device_unbind_shareUser: 'manage/device/unbind/shareUser',
	// 获取设备TDS地图数据
	manage_device_tds_map: 'manage/device/tds/map',
	// 用户绑定设备
	manage_device_iotBind: 'manage/device/iotBind',
	// 编辑设备属性
	manage_deviceProperties_saveDeviceProperties: 'manage/deviceProperties/saveDeviceProperties',
	// 编辑设备调试次数
	manage_deviceDebug_saveDeviceLeaseDebug: 'manage/deviceDebug/saveDeviceLeaseDebug',
	// 审核设备调试请求
	manage_deviceAuth_authDeviceLeaseDebug: 'manage/deviceAuth/authDeviceLeaseDebug',
	// 修正设备位置
	manage_device_reviseDeviceLocation: 'manage/device/reviseDeviceLocation',

	// *****系统管理*****
	// 新增管理员
	manage_userAccount_create: 'manage/userAccount/create',
	// 删除管理员
	manage_userAccount_delete: 'manage/userAccount/delete',
	// 禁用管理员
	manage_userAccount_forbidden: 'manage/userAccount/forbidden',
	// 管理员列表
	manage_userAccount_list: 'manage/userAccount/list',
	// 重置密码
	manage_userAccount_reset_password: 'manage/userAccount/reset/password',
	// 新增角色
	manage_role_create: 'manage/role/create',
	// 删除角色
	manage_role_delete: 'manage/role/delete',
	// 角色详情
	manage_role_detail: 'manage/role/detail',
	// 角色列表
	manage_role_list: 'manage/role/list',
	// 修改角色
	manage_role_update: 'manage/role/update',
	// 权限列表
	common_account_permission_list: 'common/account/permission/list',
	// 角色列表
	common_account_role_list: 'common/account/role/list',

	// 验证手机号是否存在
	common_account_checkPhone: 'common/account/checkPhone',
	// 验证用户名是否存在
	common_account_checkUserName: 'common/account/checkUserName',

	// ******故障*****
	// 故障列表
	manage_breakdowns_getDeviceCurrentErrorList: 'manage/breakdowns/getDeviceCurrentErrorList',
	// 故障驱势
	manage_breakdowns_getDeviceCurrentErrorTrent: 'manage/breakdowns/getDeviceCurrentErrorTrent',
	// 根据时间查询设备故障总数
	manage_breakdowns_getDeviceCurrentErrorCount: 'manage/breakdowns/getDeviceCurrentErrorCount',
	//获取故障详情
	manage_breakdowns_getBreakdownAndDealInfo: 'manage/breakdowns/getBreakdownAndDealInfo',
	// 故障设置列表
	manage_breakdown_getBreakdownList: 'manage/breakdown/getBreakdownList',
	// 删除股长列表
	manage_breakdown_deleteDeviceError: 'manage/breakdown/deleteDeviceError',
	// 故障设置编辑
	manage_breakdown_updateBreakdown: 'manage/breakdown/updateBreakdown',
	// 新增故障设置
	manage_breakdown_createBreakdown: 'manage/breakdown/createBreakdown',
	//故障禁用、启用状态
	manage_breakdown_forbidden: 'manage/breakdown/forbidden',
	// 删除故障设置
	manage_breakdown_deleteBreakdown: 'manage/breakdown/deleteBreakdown',
	// 故障预处理页面接口
	manage_breakdown_getPretreatmentList: 'manage/breakdown/getPretreatmentList',
	// 新增预处理方案
	manage_breakdown_createPretreatment: 'manage/breakdown/createPretreatment',
	// 编辑/停用处理方案
	manage_breakdown_updatePretreatment: 'manage/breakdown/updatePretreatment',
	// 删除处理方案
	manage_breakdown_deletePretreatment: 'manage/breakdown/deletePretreatment',
	// 保修列表
	manage_breakdowns_getBreakdownDealList: 'manage/breakdowns/getBreakdownDealList',

	// ******用户******
	// 用户列表
	manage_user_list: 'manage/user/list',
	// 查询用户详情
	manage_user_detail: 'manage/user/detail',
	// 用户趋势
	manage_user_trend_list: 'manage/user/trend/list',
	// 删除用户
	manage_user_delete: 'manage/user/delete',
	// 用户设备列表
	manage_user_detail_deviceList: 'manage/user/detail/deviceList',
	// 查询绑定设备的用户数量
	manage_user_bind_device_count: 'manage/user/bind/device/count',
	// 查询用户新增数
	manage_user_trend_count: 'manage/user/trend/count',

	// ******消息******
	// 消息列表
	manage_messageRecord_getMessageRecordList: 'manage/messageRecord/getMessageRecordList',
	// 消息推送历史
	manage_messageRecord_getMessageHistoryList: 'manage/messageRecord/getMessageHistoryList',
	// 消息详情列表数据
	manage_messageRecord_getMessageRecordList: 'manage/messageRecord/getMessageRecordList',
	// 消息详情
	manage_messageRecord_getMessageHistoryinfo: 'manage/messageRecord/getMessageHistoryinfo',
	// 消息类型列表
	manage_messageType_getMessageTypeList: 'manage/messageType/getMessageTypeList',
	// 删除消息记录
	manage_messageRecord_deleteMessageRecord: 'manage/messageRecord/deleteMessagePushHistory',
	// 推送规则列表
	manage_message_getMessageConfigList: 'manage/message/getMessageConfigList',
	// 启用/停用推送规则
	manage_message_updateMessageConfigStatus: 'manage/message/updateMessageConfigStatus',
	// 推送规则删除
	manage_message_deleteMessageConfig: 'manage/message/deleteMessageConfig',
	// 推送规则修改/新增
	manage_message_saveMessageConfig: 'manage/message/saveMessageConfig',
	// 消息类型列表
	manage_messageType_getMessageTypeList: 'manage/messageType/getMessageTypeList',
	// 新建/修改消息类型
	manage_messageType_saveMessageType: 'manage/messageType/saveMessageType',
	// 删除消息类型
	manage_messageType_deleteMessageType: 'manage/messageType/deleteMessageType',
	// 反馈列表接口
	manage_feedBack_list: 'manage/feedBack/list',
	// 回复反馈接口
	manage_feedBack_updateFeedBackFeedContent: 'manage/feedBack/updateFeedBackFeedContent',
	// 推送对象列表
	manage_messageSystem_getMessageSystemList: 'manage/messageSystem/getMessageSystemList',
	// 删除推送对象列表
	manage_messageSystem_deleteMessageSystem: 'manage/messageSystem/deleteMessageSystem',
	// 新增/编辑推动对象
	manage_messageSystem_saveMessageSystem: 'manage/messageSystem/saveMessageSystem',
	// 推送消息
	manage_messageRecord_systemMessagePush: 'manage/messageRecord/systemMessagePush',
	// 获取反馈详情
	manage_feedBack_detail: 'manage/feedBack/detail',

	// ******广告******
	// 广告编辑
	manage_advertise_update: 'manage/advertise/update',
	// 广告启用/停用
	manage_advertise_change: 'manage/advertise/change',
	// 广告列表
	manage_advertise_list: 'manage/advertise/list',
	// 广告添加
	manage_advertise_add: 'manage/advertise/add',
	// 广告删除
	manage_advertise_delete: 'manage/advertise/delete',
	// 获取单条详细数据
	manage_advertise_selectOne: 'manage/advertise/selectOne',

	// ******日志******

	// app用户操作日志列表
	manage_log_app_list: 'manage/log/app/list',
	// 用户操作日志详情
	manage_log_app_detail: 'manage/log/app/detail',
	// 管理后台操作日志列表
	manage_log_list: 'manage/log/list',
	// 管理后台操日志详情
	manage_log_detail: 'manage/log/detail',
	// 故障日志
	manage_breakdown_getBreakdownRecordList: 'manage/breakdown/getBreakdownRecordList',
	// 故障日志删除
	manage_breakdown_deleteHistoryDeviceError: 'manage/breakdown/deleteHistoryDeviceError',

	// ******流量卡******

	// 流量卡列表
	manage_simCard_getSimCardList: 'manage/simCard/getSimCardList',
	// 流量卡列表V2
	manage_simCard_getSimCardV2List: 'manage/simCard/getSimCardV2List',
	// 流量卡列表V2
	manage_v2_simCard_getSimCardList: '/manage/v2/simCard/getSimCardList',
	// 流量卡详情
	manage_simCard_getSimCardInfo: 'manage/simCard/getSimCardInfo',
	// 停用启用
	manage_simCard_closeSimCardGPRS: 'manage/simCard/closeSimCardGPRS',
	// 停机复机
	manage_simCard_shutAndResetSimCard: 'manage/simCard/shutAndResetSimCard',
	// 查询物联网卡套餐列表
	manage_v2_simCard_getPackageList: 'manage/v2/simCard/getPackageList',
	// 查询物联网卡套餐详情
	manage_simCard_getGPGSPackageInfo: 'manage/simCard/getGPGSPackageInfo',
	// 获取操作记录
	manage_simOperateRecord_getSimOperateRecordList: 'manage/simOperateRecord/getSimOperateRecordList',
	// 获取流量池数据
	manage_v2_simCard_getGroupFlowPool: 'manage/v2/simCard/getGroupFlowPool',
	// 刷新流量数据
	manage_v2_simCard_refresh: 'manage/v2/simCard/refresh',
	// 获取sim卡
	manage_v2_simCard_getSimCardInfo: 'manage/v2/simCard/getSimCardInfo',
	// 获取套餐信息
	manage_v2_simCard_getPackageInfo: 'manage/v2/simCard/getPackageInfo',
	// sim卡近六月流量走势
	manage_v2_simCard_getSimCardRecentFlowCount: 'manage/v2/simCard/getSimCardRecentFlowCount',
	// 停机
	manage_v2_simCard_closeSim: 'manage/v2/simCard/closeSim',
	// 复机
	manage_v2_simCard_openSim: 'manage/v2/simCard/openSim',
	// 后台开始导出数据
	manage_exportSim: 'manage/v2/simCard/exportSim',
	// 监测后台数据导出进度
	manage_progress: 'manage/v2/simCard/export/progress',

	// ******公共部分******
	// 产品列表
	common_getProductName_list: 'common/getProductName/list',
	// 故障名称列表 下拉框
	common_getErrorName_list: 'common/getErrorName/list',
	// 管理员修改密码
	account_change_password: 'account/change/password',
	// 管理员登陆
	account_login: 'account/login',
	// 管理员登出
	account_logout: 'account/logout',
	// 获取验证码图片
	common_code_getCheckCode: 'common/code/getCheckCode',
	// 图片上传接口
	common_uploadImg: 'common/uploadImg',

	// 批量操作
	getBatchOperateConfigPage: "manage/batch/operate/config/getBatchOperateConfigPage",
	// 保存批量操作配置
	saveBatchOperateConfig: 'manage/batch/operate/config/saveBatchOperateConfig',
	// 禁用操作
	batch_operate_config_forbidden: 'manage/batch/operate/config/forbidden',
	// 获取批量操作详情
	getBatchOperateConfigInfo: "manage/batch/operate/config/getBatchOperateConfigInfo",
	// 删除批量操作
	batch_operate_config_delete: 'manage/batch/operate/config/delete',
	// 根据产品获取批量操作列表
	getProductBatchOperateList: 'manage/product/operate/config/getProductBatchOperateList',
	// 获取产品已经配置的批量操作
	getBatchOperateConfigByPK: 'manage/batch/operate/config/getBatchOperateConfigByPK',
	// 保存产品配置的批量操作
	saveProductBatchOperate: 'manage/product/operate/config/saveProductBatchOperate',

	// 保存系统维护信息
	saveSystemMaintainConfig: 'manage/maintain/saveSystemMaintainConfig',
	// 获取已发送的系统维护消息内容
	getSystemMaintainConfigInfo: 'manage/maintain/getSystemMaintainConfigInfo',
}