const menu = [{
	"name": "设备产测",
	"title": "设备产测",
	"checked": true,
	"path": "/"
}, {
	"name": "秘钥烧录",
	"title": "秘钥烧录",
	"checked": true,
	"path": "/keyEnterList",
}, {
	"name": "工厂管理",
	"title": "工厂管理",
	"path": "/factory",
	"checked": true,
	"children": [{
		"name": "工厂管理",
		"title": "工厂管理",
		"path": "/factory/factoryList",
		"checked": true,
		"children": [{
			"name": "产线管理",
			"title": "产线管理",
			"checked": true
		}, {
			"name": "产线禁用启用",
			"title": "产线禁用启用",
			"checked": true
		}, {
			"name": "产线编辑",
			"title": "产线编辑",
			"checked": true
		}, {
			"name": "产线删除",
			"title": "产线删除",
			"checked": true
		}, {
			"name": "产线新增",
			"title": "产线新增",
			"checked": true
		}, {
			"name": "产线人员编辑",
			"title": "产线人员编辑",
			"checked": true
		}, {
			"name": "工厂禁用启用",
			"title": "工厂禁用启用",
			"checked": true
		}, {
			"name": "工厂编辑",
			"title": "工厂编辑",
			"checked": true
		}, {
			"name": "工厂删除",
			"title": "工厂删除",
			"checked": true
		}, {
			"name": "工厂新增",
			"title": "工厂新增",
			"checked": true
		}, ]
	}]
}, {
	"name": "产品管理",
	"title": "产品管理",
	"path": "/product",
	"checked": true,
	"children": [{
		"name": "产品列表",
		"title": "产品列表",
		"path": "/product/productList",
		"checked": true,
		"children": [{
			"name": "产品启用禁用",
			"title": "产品启用禁用",
			"checked": true
		}, {
			"name": "产品详情",
			"title": "产品详情",
			"checked": true
		}]
	}]
}, {
	"name": "设备管理",
	"title": "设备管理",
	"path": "/device",
	"checked": true,
	"children": [{
		"name": "在线设备",
		"title": "在线设备",
		"path": "/device/deviceOnline",
		"checked": true,
		"children": [{
			"name": "设备详情",
			"title": "设备详情",
			"checked": true
		}]
	}, {
		"name": "完成设备",
		"title": "完成设备",
		"path": "/device/completeList",
		"checked": true,
		"children": [{
			"name": "设备详情",
			"title": "设备详情",
			"checked": true
		}]
	}]
}, {
	"name": "固件管理",
	"title": "固件管理",
	"path": "/firmware",
	"checked": true,
	"children": [{
		"name": "固件列表",
		"title": "固件列表",
		"path": "/firmware/firmwareList",
		"checked": true,
		"children": [{
			"name": "固件删除",
			"title": "固件删除",
			"checked": true
		}, {
			"name": "固件新增",
			"title": "固件新增",
			"checked": true
		}, {
			"name": "固件修改",
			"title": "固件修改",
			"checked": true
		}, {
			"name": "固件文件下载",
			"title": "固件文件下载",
			"checked": true
		}]
	}]
}, {
	"name": "秘钥管理",
	"title": "秘钥管理",
	"path": "/key",
	"checked": true,
	"children": [{
		"name": "秘钥列表",
		"title": "秘钥列表",
		"path": "/key/keyList",
		"checked": true,
		"children": [{
			"name": "预警设置",
			"title": "预警设置",
			"checked": true
		}, {
			"name": "秘钥详情",
			"title": "秘钥详情",
			"checked": true
		}, {
			"name": "秘钥添加",
			"title": "秘钥添加",
			"checked": true
		}, {
			"name": "上传文件",
			"title": "上传文件",
			"checked": true
		}, {
			"name": "下载模板",
			"title": "上传文件",
			"checked": true
		}]
	}]
}, {
	"name": "系统管理",
	"title": "系统管理",
	"path": "/system",
	"checked": true,
	"children": [{
		"name": "用户列表",
		"title": "用户列表",
		"path": "/system/userList",
		"checked": true,
		"children": [{
			"name": "用户禁用",
			"title": "用户禁用",
			"checked": true
		}, {
			"name": "用户编辑",
			"title": "用户编辑",
			"checked": true
		}, {
			"name": "用户删除",
			"title": "用户删除",
			"checked": true
		}, {
			"name": "用户新增",
			"title": "用户新增",
			"checked": true
		}, {
			"name": "重置密码",
			"title": "重置密码",
			"checked": true
		}]
	}, {
		"name": "角色列表",
		"title": "角色列表",
		"path": "/system/roleList",
		"checked": true,
		"children": [{
			"name": "角色禁用",
			"title": "角色禁用",
			"checked": true
		}, {
			"name": "角色编辑",
			"title": "角色编辑",
			"checked": true
		}, {
			"name": "角色删除",
			"title": "角色删除",
			"checked": true
		}, {
			"name": "角色新增",
			"title": "角色新增",
			"checked": true
		}, {
			"name": "角色详细",
			"title": "角色详细",
			"checked": true
		}, {
			"name": "编辑权限",
			"title": "编辑权限",
			"checked": true
		}]
	}]
}]
export default menu